# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(upload_to='images/')),
                ('createdby', models.CharField(max_length=80)),
            ],
        ),
    ]
