# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import fossee4.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[fossee4.validators.validate_file_size]),
        ),
    ]
