# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import fossee4.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0002_auto_20190311_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[fossee4.validators.validate_file_size, fossee4.validators.validate_file_extension]),
        ),
    ]
