# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0003_auto_20190313_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ide',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
