# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0004_auto_20190316_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ide',
            field=models.IntegerField(unique=True),
        ),
    ]
