# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0005_auto_20190316_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='ide',
            new_name='uniqueId',
        ),
    ]
