# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossee4', '0006_auto_20190316_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='uniqueId',
        ),
    ]
